 Q1. Create two 3×3 matrices using the random function in Numpy and perform the following operations.
è Product (prod)
è Multiplication (multiply)
è Dot Product (dot)

In [3]:
import numpy as np

matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)

product = np.prod(matrix1)
multiplication = np.multiply(matrix1, matrix2)
dot_product = np.dot(matrix1, matrix2)

print("Product:")
print(product)
print("Multiplication:")
print(multiplication)
print("Dot Product:")
print(dot_product)



Product:
4.268142200017252e-06
Multiplication:
[[0.16847531 0.16470224 0.0243219 ]
 [0.35317708 0.6051337  0.07658854]
 [0.04339994 0.00906708 0.45795608]]
Dot Product:
[[0.44703274 0.70388547 0.30755509]
 [0.67474134 1.09876627 0.47522443]
 [0.66346126 0.73966753 0.47223924]]


Q2. Perform the following set operations using the Numpy functions.
è Union
è Intersection
è Set difference
è XOR

In [5]:
import numpy as np

set1 = np.array([1, 2, 3, 4, 5])
set2 = np.array([4, 5, 6, 7, 8])

union_set =np.union1d(set1,set2)
print(union_set)



intersection_set = np.intersect1d(set1, set2)
print(intersection_set)
difference_set = np.setdiff1d(set1,set2)
print(difference_set)

xor_set = np.setxor1d(set1, set2)
print(xor_set)


[1 2 3 4 5 6 7 8]
[4 5]
[1 2 3]
[1 2 3 6 7 8]


Q3. Create a 1D array using Random function and perform the following operations.
è Cumulative sum
è Cumulative Product
è Discrete difference (with n=3)
è Find the unique elements from the array


In [1]:
import numpy as np

array_size = 10
array = np.random.rand(array_size)

cumulative_sum = np.cumsum(array)
cumulative_product = np.cumprod(array)

n = 3
discrete_difference = np.diff(array, n)

unique_elements = np.unique(array)

print("Original Array: ", array)
print("Cumulative Sum: ", cumulative_sum)
print("Cumulative Product: ", cumulative_product)
print("Discrete Difference: ", discrete_difference)
print("Unique Elements: ", unique_elements)


Original Array:  [0.51065365 0.09904616 0.70845221 0.79900827 0.96550574 0.48543944
 0.91069927 0.70528675 0.63643226 0.31264322]
Cumulative Sum:  [0.51065365 0.60969982 1.31815203 2.11716031 3.08266605 3.56810549
 4.47880476 5.1840915  5.82052376 6.13316698]
Cumulative Product:  [0.51065365 0.05057829 0.0358323  0.0286303  0.02764272 0.01341887
 0.01222055 0.00861899 0.00548541 0.00171497]
Discrete Difference:  [-1.53986353  0.5947914  -0.72250518  1.55188991 -1.53599848  0.76723038
 -0.39149258]
Unique Elements:  [0.09904616 0.31264322 0.48543944 0.51065365 0.63643226 0.70528675
 0.70845221 0.79900827 0.91069927 0.96550574]


Q4. Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())


In [7]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
result_zip = [x + y for x, y in zip(array1, array2)]
print("Result using zip():", result_zip)
result_add = np.add(array1, array2)
print("Result using add():", result_add)
def sub(x, y):
    return x - y

sub_func = np.frompyfunc(sub, 2, 1)
result_user_defined = sub_func(array1, array2)
print("Result using user-defined function:", result_user_defined)






Result using zip(): [7, 9, 11, 13, 15]
Result using add(): [ 7  9 11 13 15]
Result using user-defined function: [-5 -5 -5 -5 -5]


Q5. Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce().

In [4]:
from functools import reduce
import numpy as np
from math import gcd


input_str = input("Enter values for the array comma-separated: ")
a = np.array([int(x) for x in input_str.split(',')])

def calculate_lcm(x, y):
    return x * y // gcd(x, y)

def calculate_gcd(x, y):
    while y != 0:
        x, y = y, x % y
    return x

lcm = reduce(calculate_lcm, a)
gcd = reduce(calculate_gcd, a)

print("LCM:", lcm)
print("GCD:", gcd)

LCM: 60
GCD: 1
